//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class vObsluga
    {
        public int ID_Obslugi { get; set; }
        public string Nazwa { get; set; }
        public int ID_Maszyny { get; set; }
        public string Producent { get; set; }
        public string Model { get; set; }
        public string Element_Nazwa { get; set; }
    }
}
