//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSrednia_ilosc_maszyn
    {
        public string Rodzaj_Maszyny { get; set; }
        public Nullable<int> srednia_ilosc_maszyn { get; set; }
    }
}
