//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class vZamowienieProcesyProdukcyjne
    {
        public int ID_Procesu_Produkcyjnego { get; set; }
        public Nullable<int> ID_Zamowienia { get; set; }
        public int ID_Zamowienie_Produkt { get; set; }
        public string Nazwa_Produktu { get; set; }
        public int ID_Proces_Technologiczny { get; set; }
        public Nullable<System.DateTime> Data_Rozpoczecia { get; set; }
        public Nullable<System.DateTime> Data_Zakonczenia { get; set; }
        public Nullable<int> ID_Dokumentacja_Proces { get; set; }
        public string Uwagi { get; set; }
    }
}
