//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamowienia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zamowienia()
        {
            this.Dostarczenia_Zewn = new HashSet<Dostarczenia_Zewn>();
            this.Faktury = new HashSet<Faktury>();
            this.Zamowienia_Dostawy = new HashSet<Zamowienia_Dostawy>();
            this.Zamowienie_Produkt = new HashSet<Zamowienie_Produkt>();
            this.Zamowienia_Przydzial = new HashSet<Zamowienia_Przydzial>();
        }
    
        public int ID_Zamowienia { get; set; }
        public Nullable<int> ID_Klienta { get; set; }
        public Nullable<System.DateTime> Data_Zlozenia { get; set; }
        public Nullable<System.DateTime> Data_Zakonczenia { get; set; }
        public Nullable<bool> Dokumentacja { get; set; }
        public Nullable<int> ID_Pracownika { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dostarczenia_Zewn> Dostarczenia_Zewn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faktury> Faktury { get; set; }
        public virtual Klienci Klienci { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienia_Dostawy> Zamowienia_Dostawy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienie_Produkt> Zamowienie_Produkt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienia_Przydzial> Zamowienia_Przydzial { get; set; }
    }
}
