//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magazyn_Umowy_Kurierzy
    {
        public int ID_Umowy { get; set; }
        public string ID_Kurier { get; set; }
        public Nullable<System.DateTime> Data_Zawarcia { get; set; }
        public Nullable<System.TimeSpan> Czas_Dostawy { get; set; }
        public Nullable<int> Koszt_Km { get; set; }
        public Nullable<int> Koszt_Staly { get; set; }
    
        public virtual Magazyn_Kurierzy Magazyn_Kurierzy { get; set; }
    }
}
