//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magazyn_Dostawcy_Zaopatrzenie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Magazyn_Dostawcy_Zaopatrzenie()
        {
            this.Magazyn_Oferta = new HashSet<Magazyn_Oferta>();
        }
    
        public string ID_Dostawcy { get; set; }
        public string Nazwa { get; set; }
        public Nullable<int> Telefon_1 { get; set; }
        public Nullable<int> Telefon_2 { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Magazyn_Oferta> Magazyn_Oferta { get; set; }
    }
}
