//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magazyn_Oferta
    {
        public string ID_Oferta { get; set; }
        public Nullable<int> ID_Element { get; set; }
        public string ID_Dostawcy { get; set; }
        public Nullable<decimal> Cena_Jedn { get; set; }
        public Nullable<decimal> Cena { get; set; }
        public string Data_Oferty { get; set; }
        public Nullable<int> Ilosc_Minimalna { get; set; }
        public Nullable<int> Ilosc_Maksymalna { get; set; }
        public Nullable<int> Ilosc_W_Opakowaniu_Zbiorczym { get; set; }
    
        public virtual Magazyn_Dostawcy_Zaopatrzenie Magazyn_Dostawcy_Zaopatrzenie { get; set; }
        public virtual Magazyn_Elementy Magazyn_Elementy { get; set; }
    }
}
